### ISSUE TITLE
Stage name is always dev?

### ISSUE THREAD

**Issue by chrille112** [sbstjn/serverless-dynamodb-autoscaling#10]
When I run `sls deploy --stage prod`, the stage name in resources are always `dev`. For example:

	$ sls deploy --stage prod

    Serverless Error ---------------------------------------
 
    An error occurred while provisioning your stack: DynamoDBAutoscaleRolePropertyTabledev
    - DynamoDBAutoscaleRolePropertyTabledev already exists

**Comment by sbstjn** [comment]
Thanks for reporting this. I will have a look into it …

**Comment by sbstjn** [comment]
I merged a fix and just triggered a deployment for version `0.3.1` which includes the fix. The new version should be on NPM in a few minutes. Would be great if you could have a look and check if your problem is fixed now.

Thanks 👍

**Comment by chrille112** [comment]
I have tested and can verify that this fixed the problem. Thanks for the quick fix! :)

**Comment by sbstjn** [comment]
Awesome! You're welcome. Thanks for using the plugin :)

I also created [an issue for serverless](https://github.com/serverless/serverless/issues/4008) about handling the region/stage configuration …
