### ISSUE TITLE
With Serverless Framework 1.22.0 doesn't work

### ISSUE THREAD

**Issue by mavi888** [sbstjn/serverless-dynamodb-autoscaling#26]
Hello, 

I have been using this plugin for a while and now I updated to one of the latest version of serverless framework(v1.22) and it doesn't create the autoscaling of the tables anymore. 

In v1.19 it works fine, so if i switch the framework version and keep the same code everything works as expected. 

Any idea what can be happening?

**Comment by sbstjn** [comment]
Could be related to a deprecation of some internal serverless hooks. In an other plugin I had to change the configured hook to get it working again.

I will check if it can be fixed with the fix that is used in https://github.com/sbstjn/serverless-sqs-alarms-plugin/pull/8

**Comment by sbstjn** [comment]
#27 works fine in `1.23.0`. I will release a new version of the plugin …

**Comment by sbstjn** [comment]
Could you give `v0.6.2` a try and check if you problem is resolved with the updated version?
