### ISSUE TITLE
CloudFormation rate limit

### ISSUE THREAD

**Issue by sbstjn** [sbstjn/serverless-dynamodb-autoscaling#3]
The CloudFormation stack might fail due to API rate limits. @BrettFieber reported an issue and provided example configuration in the [Serverless Forums](http://forum.serverless.com/t/autoscaling-for-amazon-dynamodb/2071/5).

A solution could be to make more use of the *DependsOn* feature and apply every Auto Scaling only after the previous is done.

**Serverless Configuration**
https://gist.github.com/BrettFieber/019708518fd2ce4307ba03a360f20551

**Comment by sbstjn** [comment]
https://github.com/sbstjn/serverless-dynamodb-autoscaling/issues/4 covers the same issue

**Comment by sbstjn** [comment]
I just released `v0.2.0` which should prevent this. But there is a breaking change in the configuration.

**Comment by medikoo** [comment]
@BrettFieber did you investigate which exactly limits where exceeded in your case, the `Rate exceeded` message from AWS is pretty vague and doesn't expose details.

Was it `PutMetricAlarm` transactions per second limit? Or something else?

I wonder for which exactly limit do #7 update applies as workaround (?)

**Comment by mataide** [comment]
isnt possible to solve this limit problem without ask AWS to upgrade?
