### ISSUE TITLE
Consider no compilation involved version

### ISSUE THREAD

**Issue by medikoo** [sbstjn/serverless-dynamodb-autoscaling#30]
I wanted to contribute to this repository, still implied complication step pushes me back (makes maintenance and eventual updates additionally more complicated. I'm also not that familiar with TypeScript)

It'll be great if project is written in plain directly consumable JavaScript, in same way as [Serverless](https://github.com/serverless/serverless/) framework is (for which this is meant to be a plugin)

**Comment by sbstjn** [comment]
Sorry, this will not happen.

Give TypeScript a try and you will love it. Nobody should write plain JavaScript anymore ;)

**Comment by medikoo** [comment]
@sbstjn ok

As I didn't want invest time into setup that involves TypeScript and transpilation, I've came up with a plain JS version: https://github.com/medikoo/serverless-plugin-dynamodb-autoscaling

All the best with your project.
