### ISSUE TITLE
Use AWS::AutoScalingPlans::ScalingPlan

### ISSUE THREAD

**Issue by hassankhan** [sbstjn/serverless-dynamodb-autoscaling#43]
From what I understand, using the new `ScalingPlan` resource we can specify plans for multiple resources. This would mean that this plugin only adds a single resource to a Serverless stack, instead of two per-table.

https://aws.amazon.com/about-aws/whats-new/2018/05/aws-auto-scaling-scaling-plans-can-now-be-created-using-aws-cloudformation

**Comment by delprofundo** [comment]
> From what I understand, using the new `ScalingPlan` resource we can specify plans for multiple resources. 

Thanks for pointing this out. I was about to add scaling resources to about 15 tables. I've added two this way and its working.

**Comment by hassankhan** [comment]
For what its' worth, we ended up creating a plugin with the same options (so it should be a direct replacement): https://github.com/EndemolShineGroup/serverless-dynamodb-autoscaler
